### ISSUE TITLE
feedlint doesnt run on windows ImportError: No module named gobject

### ISSUE THREAD

**Issue by pmiess** [0install/0install-feeds#1]
0install run http://0install.net/2007/interfaces/FeedLint.xml http://0install.net/2007/interfaces/FeedLint.xml
Traceback (most recent call last):
  File "C:\ProgramData\0install.net\implementations\sha256new_TGEZYDFL3HZBTFMTM4LVDL4SOLYTORIYAAIIVQXUHYMLYOUL44YQ\feedlint", line 11, in <module>
    from zeroinstall import SafeException
  File "C:\ProgramData\0install.net\implementations\sha256new_FOGTP26G26DZHEXXPPFXLEBO2Q6TUHGRTSVJ5ZCOAUGKVSZROIVQ\zeroinstall\__init__.py", line 25, in <module>
    import gobject
ImportError: No module named gobject

Probably needs GTK also.

**Comment by talex5** [comment]
I've now added a gobject dependency to older versions of 0install too, to stop the C# solver from picking them. I'd prefer not to add a dependency from feedlint itself because (unlike 0compile) it doesn't use gobject directly, but only via 0install.

It might make solving a bit slow on Windows though, until the solver is updated (or someone publishes a 64-bit version of gobject for Windows).
